baseurl: "https://example.com"
languageCode: "en-us"
title: "Asdita Prasetya"
theme: "hugo-tania"
paginate: 6

params:
  # Emoji will show before the blog title on site navbar.
  titleEmoji: 'ðŸ˜Ž'

  # Logo will show before the blog title on site navbar.
  titleLogo:
  
  # Enable float footnotes.
  # Default to true
  enableFootnotes: true
  siteName: "Asdita Prasetya"
  siteDesc: "Asdita Prasetya Official Web"
  author: "Asdita Prasetya"


  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow: 10

  # Show your socail information with icon on index bio with `_index.md` content.
  socialOptions:
    email: asditap@gmail.com
    medium: "https://medium.com/hellodit"
    github: https://github.com/hellodit
    twitter: "https://twitter.com/asditaprasetya"
    linkedin: "https://www.linkedin.com/in/asditaprasetya/"


menu:
  header:
    - name: Articles
      url: "/articles/"
  footer:
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "RSS", "JSON"]